Add necessary RBAC permission for mongodb and mysql
kubestash/installer pull request #31
Opened 2023-11-16 12:31 UTC by anisurrahman75

2023-11-16 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubestash/installer?pullRequest=31) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubestash/installer?pullRequest=31) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubestash/installer?pullRequest=31) it.</sub>

2023-11-20 04:37 UTC, ishtiaqhimel approved these changes

2023-11-23 14:06 UTC, hmsayem approved these changes

2023-11-23 14:15 UTC, hmsayem requested changes

2023-11-23 14:15 UTC, hmsayem commented on charts/kubestash-operator/templates/rbac/cluster_role.yaml
> +      - elasticsearchversions
do we need `elasticsearchversions` ?

2023-11-27 08:11 UTC, hmsayem approved these changes

2023-11-27 08:48 UTC, merged